language: node_js
dist: trusty
node_js:
  - "6"
sudo: true
before_install:
  - openssl aes-256-cbc -K $encrypted_b32679098817_key -iv $encrypted_b32679098817_iv -in id_rsa.enc -out id_rsa -d
  - mv id_rsa ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # - sudo apt-get update
  # - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -O ~/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i ~/google-chrome*.deb
  - npm install -g angular-cli

before_script:
  - npm install
script:
  - git status
  - ng github-pages:deploy --message "travis build $TRAVIS_BUILD_NUMBER"

# whitelist
branches:
  only:
    - master
